version: "3"

env:
  smv_dart_directory: ./packages/smv_dart
  smv_typescript_directory: ./packages/smv_typescript
tasks:
  flutter:clean:
    dir: "{{.smv_dart_directory}}"
    cmds:
      - flutter clean
  flutter:download:
    dir: "{{.smv_dart_directory}}"
    cmds:
      - flutter pub get
  flutter:upgrade:
    dir: "{{.smv_dart_directory}}"
    cmds:
      - flutter pub upgrade
  flutter:outdated:
    dir: "{{.smv_dart_directory}}"
    cmds:
      - flutter pub outdated
  flutter:test:
    dir: "{{.smv_dart_directory}}"
    cmds:
      - flutter test
  npm:download:
    dir: "{{.smv_typescript_directory}}"
    cmds:
      - rm -rf node_modules/
      - rm -rf package-lock.json
      - npm run download
  npm:build:
    dir: "{{.smv_typescript_directory}}"
    cmds:
      - rm -rf dist/
      - npm run build
  npm:test:
    dir: "{{.smv_typescript_directory}}"
    cmds:
      - npm run test
  npm:drypack:
    dir: "{{.smv_typescript_directory}}"
    cmds:
      - npm run drypack
  npm:pack:
    dir: "{{.smv_typescript_directory}}"
    cmds:
      - npm run pack