name: packages_smvgo_running_unit_tests
run-name: ${{ github.actor }}
on:
  push:
    paths:
        - "packages/smvgo/**"
  workflow_dispatch:
env:
  go_version: 1.27.0
  task_version: 3.45.4
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ env.go_version }}
      - uses: go-task/setup-task@v2
        with:
          version: ${{ env.task_version }}
      - run: task go:download
      - run: task go:test
