name: packages_smv_dart_running_unit_tests
run-name: ${{ github.actor }}
on:
  push:
    paths:
        - "packages/smv_dart/**"
  workflow_dispatch:
env:
  flutter_channel: stable
  task_version: 3.45.4
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - uses: go-task/setup-task@v2
        with:
          version: ${{ env.task_version }}
      - run: task flutter:download
      - run: task flutter:test