name: packages_smv_typescript_running_unit_tests
run-name: ${{ github.actor }}
on:
  push:
    paths:
        - "packages/smv_typescript/**"
  workflow_dispatch:
env:
  node_version: 24.7.0
  task_version: 3.45.4
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.node_version }}
      - uses: go-task/setup-task@v2
        with:
          version: ${{ env.task_version }}
      - run: task npm:download
      - run: task npm:test